name: CI Pipeline

on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Echo secret
        run: echo "Using API key: ${{ secrets.FAKE_API_KEY }}"

      - name: Save test logs
        run: |
          mkdir -p logs
          echo "Test logs for build" > logs/test.log

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: logs/


